import { useCallback, useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { Alert, Badge, Box, Button, Card, CardActionArea, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Pagination, Paper, Select, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from "@mui/material";
import AddShoppingCartOutlinedIcon from "@mui/icons-material/AddShoppingCartOutlined";
import CategoryOutlinedIcon from "@mui/icons-material/CategoryOutlined";
import ImageOutlinedIcon from "@mui/icons-material/ImageOutlined";
import ReceiptLongOutlinedIcon from "@mui/icons-material/ReceiptLongOutlined";
import ShoppingCartOutlinedIcon from "@mui/icons-material/ShoppingCartOutlined";
import { BusyButton, EmptyState, ErrorState, LoadingState, PageHeader, SectionCard } from "./foundation";

type ApiError = Error & { status?: number };
type Branch = { id: string; code: string; nameAr: string; nameEn: string | null };
type Category = { id: string; code: string; nameAr: string; nameEn: string };
type CatalogItem = { branchItemId: string; sku: string; barcode: string | null; imageAvailable: boolean; categoryId: string; nameAr: string; nameEn: string; nameUr: string };
type CatalogPage = { page: number; pageSize: number; total: number; data: CatalogItem[] };
type ItemUnit = { id: string; code: string; nameAr: string; nameEn: string; isBaseUnit: boolean };
type RequestLine = { id: string; branchItemId: string; itemId: string; itemUnitId: string; item: { nameAr: string; nameEn: string; nameUr: string }; sku: string; unit: { code: string; nameAr: string; nameEn: string }; requestedQuantity: string; lineStatus: "active" | "excluded"; addedAfterFirstSubmission: boolean };
type RequestDetail = { id: string; requestNumber: string; branch: Branch; status: "draft" | "returned" | "pending_approval" | "ready" | "approved" | "rejected" | "cancelled"; rowVersion: number; submittedAt: string | null; items: RequestLine[] };
type RequestList = { page: number; pageSize: number; total: number; data: Array<{ id: string; requestNumber: string; branch: Branch; status: RequestDetail["status"]; submittedAt: string | null; activeLineCount: number; rowVersion: number }> };

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, { credentials: "same-origin", ...init });
  const payload = await response.json().catch(() => null) as { message?: string } | T | null;
  if (!response.ok) { const error = new Error(typeof payload === "object" && payload && "message" in payload ? String(payload.message) : `HTTP ${response.status}`) as ApiError; error.status = response.status; throw error; }
  return payload as T;
}
async function csrf() { return api<{ csrfToken: string }>("/api/v1/auth/csrf", { cache: "no-store" }); }
async function mutation<T>(path: string, method: "POST" | "PATCH" | "DELETE", body?: unknown): Promise<T> { const token = await csrf(); return api<T>(path, { method, headers: { "Content-Type": "application/json", "X-CSRF-Token": token.csrfToken }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); }
const message = (caught: unknown, fallback: string) => caught instanceof Error ? caught.message : fallback;

function localized(value: { nameAr: string; nameEn: string; nameUr?: string | null }, language: string) {
  return language.startsWith("ur") ? value.nameUr || value.nameEn || value.nameAr : language.startsWith("en") ? value.nameEn || value.nameAr : value.nameAr;
}

export function RequisitionPage({ online }: { online: boolean }) {
  const { i18n, t } = useTranslation();
  const [branches, setBranches] = useState<Branch[]>([]); const [branchId, setBranchId] = useState(""); const [categories, setCategories] = useState<Category[]>([]); const [categoryId, setCategoryId] = useState(""); const [items, setItems] = useState<CatalogPage | null>(null); const [search, setSearch] = useState(""); const [page, setPage] = useState(1);
  const [request, setRequest] = useState<RequestDetail | null>(null); const [history, setHistory] = useState<RequestList | null>(null); const [activeTab, setActiveTab] = useState<"catalog" | "history">("catalog"); const [selection, setSelection] = useState<CatalogItem | null>(null); const [units, setUnits] = useState<ItemUnit[]>([]); const [unitId, setUnitId] = useState(""); const [quantity, setQuantity] = useState("1"); const [cartOpen, setCartOpen] = useState(false); const [confirmOpen, setConfirmOpen] = useState(false); const [editingLine, setEditingLine] = useState<RequestLine | null>(null); const [editUnits, setEditUnits] = useState<ItemUnit[]>([]); const [editUnitId, setEditUnitId] = useState(""); const [editQuantity, setEditQuantity] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);

  const loadBranches = useCallback(async () => { if (!online) return; setLoading(true); try { setBranches(await api<Branch[]>("/api/v1/requisition/branches")); } catch (caught) { setError(message(caught, "تعذر تحميل بيانات الطلب.")); } finally { setLoading(false); } }, [online]);
  useEffect(() => { void loadBranches(); }, [loadBranches]);
  const loadCategories = useCallback(async () => { if (!branchId || !online) return; try { setCategories(await api<Category[]>(`/api/v1/requisition/branches/${branchId}/categories`)); } catch (caught) { setError(message(caught, "تعذر تحميل بيانات الطلب.")); } }, [branchId, online]);
  useEffect(() => { void loadCategories(); }, [loadCategories]);
  const loadItems = useCallback(async () => { if (!branchId || !categoryId || !online) return; setLoading(true); try { const params = new URLSearchParams({ page: String(page), pageSize: "24" }); if (search.trim()) params.set("search", search.trim()); setItems(await api<CatalogPage>(`/api/v1/requisition/branches/${branchId}/categories/${categoryId}/items?${params}`)); } catch (caught) { setError(message(caught, "تعذر تحميل بيانات الطلب.")); } finally { setLoading(false); } }, [branchId, categoryId, online, page, search]);
  useEffect(() => { void loadItems(); }, [loadItems]);
  const loadHistory = useCallback(async () => { if (!online) return; try { setHistory(await api<RequestList>("/api/v1/requisitions?page=1&pageSize=30")); } catch (caught) { setError(message(caught, "تعذر تحميل بيانات الطلب.")); } }, [online]);
  useEffect(() => { if (activeTab === "history") void loadHistory(); }, [activeTab, loadHistory]);
  const createDraft = async () => { if (!branchId || !online) return null; setBusy(true); try { const detail = await mutation<RequestDetail>("/api/v1/requisitions", "POST", { branchId }); setRequest(detail); return detail; } catch (caught) { setError(message(caught, t("requisitionSaveFailed"))); return null; } finally { setBusy(false); } };
  const choose = async (item: CatalogItem) => { if (!online) return; setBusy(true); setError(null); try { const detail = request ?? await createDraft(); if (!detail) return; setRequest(detail); const available = await api<ItemUnit[]>(`/api/v1/requisition/branch-items/${item.branchItemId}/units`); setSelection(item); setUnits(available); setUnitId(available[0]?.id ?? ""); setQuantity("1"); } catch (caught) { setError(message(caught, t("requisitionLoadFailed"))); } finally { setBusy(false); } };
  const addLine = async () => { if (!selection || !request || !unitId || !online) return; setBusy(true); try { const result = request.status === "returned" ? await mutation<RequestDetail>(`/api/v1/requisitions/${request.id}/returned-items`, "POST", { branchItemId: selection.branchItemId, itemUnitId: unitId, requestedQuantity: quantity, expectedRowVersion: request.rowVersion }) : await mutation<RequestDetail>(`/api/v1/requisitions/${request.id}/items`, "POST", { branchItemId: selection.branchItemId, itemUnitId: unitId, requestedQuantity: quantity, expectedRowVersion: request.rowVersion }); setRequest(result); setSelection(null); } catch (caught) { setError(message(caught, t("requisitionSaveFailed"))); } finally { setBusy(false); } };
  const removeLine = async (line: RequestLine) => { if (!request || !online) return; setBusy(true); try { setRequest(await mutation<RequestDetail>(`/api/v1/requisitions/${request.id}/items/${line.id}?expectedRowVersion=${request.rowVersion}`, "DELETE")); } catch (caught) { setError(message(caught, t("requisitionSaveFailed"))); } finally { setBusy(false); } };
  const beginEditLine = async (line: RequestLine) => { if (!request || !online) return; setBusy(true); setError(null); try { const available = await api<ItemUnit[]>(`/api/v1/requisition/branch-items/${line.branchItemId}/units`); setEditUnits(available); setEditUnitId(line.itemUnitId); setEditQuantity(line.requestedQuantity); setEditingLine(line); } catch (caught) { setError(message(caught, t("requisitionLoadFailed"))); } finally { setBusy(false); } };
  const saveLineEdit = async () => { if (!request || !editingLine || !editUnitId || !online) return; setBusy(true); try { const result = await mutation<RequestDetail>(`/api/v1/requisitions/${request.id}/items/${editingLine.id}`, "PATCH", { branchItemId: editingLine.branchItemId, itemUnitId: editUnitId, requestedQuantity: editQuantity, expectedRowVersion: request.rowVersion }); setRequest(result); setEditingLine(null); } catch (caught) { setError(message(caught, t("requisitionSaveFailed"))); } finally { setBusy(false); } };
  const submit = async () => { if (!request || !online) return; setBusy(true); try { const endpoint = request.status === "returned" ? "resubmit" : "submit"; setRequest(await mutation<RequestDetail>(`/api/v1/requisitions/${request.id}/${endpoint}`, "POST", { expectedRowVersion: request.rowVersion })); setConfirmOpen(false); await loadHistory(); } catch (caught) { setError(message(caught, t("requisitionSubmitFailed"))); setConfirmOpen(false); } finally { setBusy(false); } };
  const activeLines = request?.items.filter((line) => line.lineStatus === "active") ?? [];
  const pageCount = Math.max(1, Math.ceil((items?.total ?? 0) / 24));

  return (
    <Box>
      <PageHeader eyebrow="PHASE 5 · BRANCH REQUISITION" title={t("requisitions")} description={t("requisitionDescription")} actions={<Box sx={{ display: "flex", gap: 1, flexWrap: "wrap" }}><Badge badgeContent={activeLines.length} color="secondary"><Button disabled={!request} onClick={() => setCartOpen(true)} startIcon={<ShoppingCartOutlinedIcon />} variant="outlined">{t("cart")}</Button></Badge><Button onClick={() => setActiveTab(activeTab === "catalog" ? "history" : "catalog")} startIcon={<ReceiptLongOutlinedIcon />} variant="text">{activeTab === "catalog" ? t("myRequests") : t("catalog")}</Button></Box>} />
      {!online && <Alert severity="warning" sx={{ mb: 2 }}>{t("requisitionOffline")}</Alert>}
      {error && <Alert onClose={() => setError(null)} severity="error" sx={{ mb: 2 }}>{error}</Alert>}
      {activeTab === "history" ? <RequestHistory history={history} language={i18n.language} loading={loading} onOpen={async (id) => { try { setRequest(await api<RequestDetail>(`/api/v1/requisitions/${id}`)); setCartOpen(true); } catch (caught) { setError(message(caught, t("requisitionLoadFailed"))); } }} t={t} /> : <>
        <SectionCard title={t("selectBranchAndCategory")}><Box sx={{ display: "grid", gap: 1.5, gridTemplateColumns: { xs: "1fr", md: "minmax(0, 1fr) minmax(0, 1fr) auto" } }}><FormControl><InputLabel id="requisition-branch">{t("branch")}</InputLabel><Select label={t("branch")} labelId="requisition-branch" onChange={(event) => { setBranchId(event.target.value); setCategoryId(""); setItems(null); setPage(1); }} value={branchId}><MenuItem value="">{t("selectBranch")}</MenuItem>{branches.map((branch) => <MenuItem key={branch.id} value={branch.id}>{branch.code} · {localized({ nameAr: branch.nameAr, nameEn: branch.nameEn ?? branch.nameAr }, i18n.language)}</MenuItem>)}</Select></FormControl><TextField disabled={!branchId} label={t("searchCatalog")} onChange={(event) => { setPage(1); setSearch(event.target.value); }} value={search} /><Button disabled={!branchId || busy || !online} onClick={() => void createDraft()} startIcon={<AddShoppingCartOutlinedIcon />} variant="contained">{request ? t("draftReady") : t("startDraft")}</Button></Box></SectionCard>
        {!branchId ? <Box sx={{ mt: 2 }}><SectionCard><EmptyState title={t("selectBranch")} message={t("selectBranchHint")} /></SectionCard></Box> : loading && !categories.length ? <LoadingState title={t("loadingTitle")} message={t("catalogLoading")} /> : <>
          <Typography component="h2" sx={{ fontWeight: 800, mt: 3, mb: 1.5 }} variant="h6">{t("categories")}</Typography>
          <Box sx={{ display: "grid", gap: 1.5, gridTemplateColumns: { xs: "repeat(2, minmax(0, 1fr))", sm: "repeat(3, minmax(0, 1fr))", lg: "repeat(5, minmax(0, 1fr))" } }}>{categories.map((category) => <Card key={category.id} variant={categoryId === category.id ? "elevation" : "outlined"} sx={{ borderColor: categoryId === category.id ? "primary.main" : undefined }}><CardActionArea onClick={() => { setPage(1); setCategoryId(category.id); }} sx={{ minHeight: 112 }}><CardContent><CategoryOutlinedIcon color="primary" /><Typography sx={{ fontWeight: 800, mt: 1 }}>{localized(category, i18n.language)}</Typography><Typography color="text.secondary" variant="caption">{category.code}</Typography></CardContent></CardActionArea></Card>)}</Box>
          {categoryId && (loading ? <LoadingState title={t("loadingTitle")} message={t("catalogLoading")} /> : !items?.data.length ? <Box sx={{ mt: 2 }}><SectionCard><EmptyState title={t("catalogEmpty")} message={t("catalogEmptyHint")} /></SectionCard></Box> : <><Box sx={{ alignItems: "center", display: "flex", justifyContent: "space-between", mt: 3, mb: 1 }}><Typography component="h2" sx={{ fontWeight: 800 }} variant="h6">{t("items")}</Typography><Typography color="text.secondary" variant="body2">{t("records", { count: items.total })}</Typography></Box><Box sx={{ display: "grid", gap: 1.5, gridTemplateColumns: { xs: "1fr", sm: "repeat(2, minmax(0, 1fr))", lg: "repeat(3, minmax(0, 1fr))" } }}>{items.data.map((item) => <Card key={item.branchItemId} variant="outlined"><CardActionArea disabled={!online || busy} onClick={() => void choose(item)} sx={{ minHeight: 166 }}><CardContent sx={{ display: "grid", gap: 1 }}><Box sx={{ alignItems: "center", display: "flex", gap: 1 }}><Box sx={{ alignItems: "center", bgcolor: "primary.light", borderRadius: 2, color: "primary.main", display: "flex", height: 42, justifyContent: "center", width: 42 }}>{item.imageAvailable ? <ImageOutlinedIcon /> : <CategoryOutlinedIcon />}</Box><Box sx={{ minWidth: 0 }}><Typography noWrap sx={{ fontWeight: 800 }}>{localized(item, i18n.language)}</Typography><Typography color="text.secondary" variant="caption">{item.sku}</Typography></Box></Box><Chip color="primary" label={t("chooseQuantityUnit")} size="small" variant="outlined" /></CardContent></CardActionArea></Card>)}</Box><Box sx={{ display: "flex", justifyContent: "center", mt: 2 }}><Pagination count={pageCount} onChange={(_, value) => setPage(value)} page={page} /></Box></>)}
        </>}
      </>}
      {selection && <QuantityDialog busy={busy} item={selection} language={i18n.language} onClose={() => setSelection(null)} onSave={() => void addLine()} quantity={quantity} setQuantity={setQuantity} setUnitId={setUnitId} t={t} unitId={unitId} units={units} />}
      {cartOpen && request && <CartDialog busy={busy} language={i18n.language} online={online} onClose={() => setCartOpen(false)} onEdit={(line) => void beginEditLine(line)} onRemove={(line) => void removeLine(line)} onSubmit={() => setConfirmOpen(true)} request={request} t={t} />}
      {editingLine && <CartLineEditDialog busy={busy} language={i18n.language} line={editingLine} onClose={() => setEditingLine(null)} onSave={() => void saveLineEdit()} quantity={editQuantity} setQuantity={setEditQuantity} setUnitId={setEditUnitId} t={t} unitId={editUnitId} units={editUnits} />}
      {confirmOpen && <Dialog fullWidth maxWidth="xs" onClose={() => setConfirmOpen(false)} open><DialogTitle>{t(request?.status === "returned" ? "confirmResubmit" : "confirmSubmit")}</DialogTitle><DialogContent><Typography>{t("submitNotice")}</Typography></DialogContent><DialogActions><Button onClick={() => setConfirmOpen(false)}>{t("cancel")}</Button><BusyButton busy={busy} onClick={() => void submit()} variant="contained">{t(request?.status === "returned" ? "resubmit" : "submit")}</BusyButton></DialogActions></Dialog>}
    </Box>
  );
}

function QuantityDialog({ item, units, unitId, setUnitId, quantity, setQuantity, busy, language, onClose, onSave, t }: { item: CatalogItem; units: ItemUnit[]; unitId: string; setUnitId: (value: string) => void; quantity: string; setQuantity: (value: string) => void; busy: boolean; language: string; onClose: () => void; onSave: () => void; t: (key: string, values?: Record<string, unknown>) => string }) {
  return <Dialog fullWidth maxWidth="xs" onClose={onClose} open><DialogTitle>{t("chooseQuantityUnit")}</DialogTitle><DialogContent><Box sx={{ display: "grid", gap: 2, pt: 1 }}><Typography sx={{ fontWeight: 800 }}>{localized(item, language)}</Typography><TextField label={t("quantity")} onChange={(event) => setQuantity(event.target.value)} required type="number" value={quantity} /><FormControl><InputLabel id="request-unit">{t("unit")}</InputLabel><Select label={t("unit")} labelId="request-unit" onChange={(event) => setUnitId(event.target.value)} value={unitId}>{units.map((unit) => <MenuItem key={unit.id} value={unit.id}>{unit.code} · {localized({ nameAr: unit.nameAr, nameEn: unit.nameEn }, language)}</MenuItem>)}</Select></FormControl></Box></DialogContent><DialogActions><Button onClick={onClose}>{t("cancel")}</Button><BusyButton busy={busy} disabled={!unitId || Number(quantity) <= 0} onClick={onSave} startIcon={<AddShoppingCartOutlinedIcon />} variant="contained">{t("addToCart")}</BusyButton></DialogActions></Dialog>;
}

function CartLineEditDialog({ line, units, unitId, setUnitId, quantity, setQuantity, busy, language, onClose, onSave, t }: { line: RequestLine; units: ItemUnit[]; unitId: string; setUnitId: (value: string) => void; quantity: string; setQuantity: (value: string) => void; busy: boolean; language: string; onClose: () => void; onSave: () => void; t: (key: string, values?: Record<string, unknown>) => string }) {
  return <Dialog fullWidth maxWidth="xs" onClose={onClose} open><DialogTitle>{t("editRecord", { name: localized(line.item, language) })}</DialogTitle><DialogContent><Box sx={{ display: "grid", gap: 2, pt: 1 }}><Typography sx={{ fontWeight: 800 }}>{localized(line.item, language)}</Typography><TextField label={t("quantity")} onChange={(event) => setQuantity(event.target.value)} required type="number" value={quantity} /><FormControl><InputLabel id="cart-edit-unit">{t("unit")}</InputLabel><Select label={t("unit")} labelId="cart-edit-unit" onChange={(event) => setUnitId(event.target.value)} value={unitId}>{units.map((unit) => <MenuItem key={unit.id} value={unit.id}>{unit.code} · {localized({ nameAr: unit.nameAr, nameEn: unit.nameEn }, language)}</MenuItem>)}</Select></FormControl></Box></DialogContent><DialogActions><Button onClick={onClose}>{t("cancel")}</Button><BusyButton busy={busy} disabled={!unitId || Number(quantity) <= 0} onClick={onSave} variant="contained">{t("save")}</BusyButton></DialogActions></Dialog>;
}

function CartDialog({ request, busy, online, onClose, onEdit, onRemove, onSubmit, language, t }: { request: RequestDetail; busy: boolean; online: boolean; onClose: () => void; onEdit: (line: RequestLine) => void; onRemove: (line: RequestLine) => void; onSubmit: () => void; language: string; t: (key: string, values?: Record<string, unknown>) => string }) {
  const active = request.items.filter((line) => line.lineStatus === "active"); const editable = request.status === "draft" || request.status === "returned"; const statusKey = request.status === "ready" ? "request_ready" : request.status;
  return <Dialog fullScreen={false} fullWidth maxWidth="md" onClose={onClose} open><DialogTitle>{t("cartReview")} · {request.requestNumber}</DialogTitle><DialogContent>{!online && <Alert severity="warning" sx={{ mb: 2 }}>{t("requisitionOffline")}</Alert>}{!active.length ? <EmptyState title={t("cartEmpty")} message={t("cartEmptyHint")} /> : <TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>{t("item")}</TableCell><TableCell>{t("unit")}</TableCell><TableCell>{t("quantity")}</TableCell><TableCell>{t("status")}</TableCell><TableCell align="right">{t("actions")}</TableCell></TableRow></TableHead><TableBody>{active.map((line) => <TableRow key={line.id}><TableCell>{localized(line.item, language)}<Typography color="text.secondary" variant="caption" sx={{ display: "block" }}>{line.sku}</Typography></TableCell><TableCell>{localized({ nameAr: line.unit.nameAr, nameEn: line.unit.nameEn }, language)}</TableCell><TableCell>{line.requestedQuantity}</TableCell><TableCell><Chip label={t(statusKey)} size="small" /></TableCell><TableCell align="right">{editable && <Box sx={{ display: "inline-flex", flexWrap: "wrap", gap: 0.5, justifyContent: "flex-end" }}><Button disabled={busy || !online} onClick={() => onEdit(line)} size="small">{t("editRecord", { name: localized(line.item, language) })}</Button><Button color="warning" disabled={busy || !online} onClick={() => onRemove(line)} size="small">{t("remove")}</Button></Box>}</TableCell></TableRow>)}</TableBody></Table></TableContainer>}</DialogContent><DialogActions><Button onClick={onClose}>{t("close")}</Button>{editable && <BusyButton busy={busy} disabled={!active.length || !online} onClick={onSubmit} variant="contained">{t(request.status === "returned" ? "resubmit" : "submit")}</BusyButton>}</DialogActions></Dialog>;
}

function RequestHistory({ history, loading, onOpen, language, t }: { history: RequestList | null; loading: boolean; onOpen: (id: string) => void; language: string; t: (key: string, values?: Record<string, unknown>) => string }) {
  if (loading && !history) return <LoadingState title={t("loadingTitle")} message={t("requisitionLoading")} />;
  if (!history?.data.length) return <SectionCard><EmptyState title={t("requestsEmpty")} message={t("requestsEmptyHint")} /></SectionCard>;
  return <SectionCard title={t("myRequests")}><TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>{t("requestNumber")}</TableCell><TableCell>{t("branch")}</TableCell><TableCell>{t("status")}</TableCell><TableCell>{t("cart")}</TableCell><TableCell align="right">{t("actions")}</TableCell></TableRow></TableHead><TableBody>{history.data.map((entry) => <TableRow key={entry.id}><TableCell>{entry.requestNumber}</TableCell><TableCell>{localized({ nameAr: entry.branch.nameAr, nameEn: entry.branch.nameEn ?? entry.branch.nameAr }, language)}</TableCell><TableCell><Chip label={t(entry.status === "ready" ? "request_ready" : entry.status)} size="small" /></TableCell><TableCell>{entry.activeLineCount}</TableCell><TableCell align="right"><Button onClick={() => onOpen(entry.id)} size="small">{t("open")}</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer></SectionCard>;
}
